# Generated by Django 5.2.6 on 2025-10-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='короткое название задачи(до255 символлв)', max_length=255, verbose_name='название задачи')),
                ('status', models.CharField(choices=[('created', 'sozdanie'), ('in_progress', 'V rabote'), ('completed', 'zaversheno')], default='created', help_text='tekushi status zadachi', max_length=20, verbose_name='status zadachi')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='vremia, kogda zadacha bylo sozdana', verbose_name='data zadanie')),
            ],
        ),
    ]
